---
name: GPSD Home Assistant add-on
version: "1.0.0"
slug: gpsd
description: Connect GPS and other GNSS devices to Home Assistant and share them on your network.
url: "https://github.com/bencorrado/addons-bencorrado/tree/main/gpsd"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
homeassistant: 0.26
options:
  device: null
  log_level: info
uart: true
ports:
  2947/tcp: 2947
#image: "ghcr.io/bencorrado/{arch}-addon-gpsd"
schema:
  device: device(subsystem=tty)
  log_level: list(silly|debug|verbose|http|info|warn|error)?
stage: experimental
startup: services
watchdog: tcp://[HOST]:[PORT:2947]